### PR TITLE
Update config handling with tests

### PR DESCRIPTION
**Pull request by NeonDaniel**
Updates STT module loader methods to pass complete configuration to Factory methods, including default language config

### CODE REVIEW

**Comment by goldyfruit** [comment]
Initial start:

```
2023-05-31 18:46:10.318 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-05-31 18:46:10.526 - OVOS - ovos_utils.configuration:get_xdg_base:76 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-05-31 18:46:14.326 - voice - ovos_dinkum_listener.service:__init__:123 - INFO - Starting Voice Service
2023-05-31 18:46:14.430 - voice - ovos_dinkum_listener.service:on_alive:58 - INFO - DinkumVoiceService is alive.
2023-05-31 18:46:14.434 - voice - ovos_dinkum_listener.service:_before_start:280 - INFO - Starting service...
2023-05-31 18:46:14.449 - voice - ovos_bus_client.conf:load_message_bus_config:19 - DEBUG - Loading message bus configs
2023-05-31 18:46:14.455 - voice - ovos_dinkum_listener.service:_connect_to_bus:372 - DEBUG - Starting bus connection
2023-05-31 18:46:14.510 - voice - ovos_bus_client.client.client:on_open:85 - DEBUG - Connected
2023-05-31 18:46:14.565 - voice - ovos_bus_client.session:from_message:184 - DEBUG - Creating default session on reference
2023-05-31 18:46:14.576 - voice - ovos_bus_client.session:reset_default_session:225 - INFO - New Default Session Start: fdf5181a-6e74-4ba0-a08a-56c4b50e2310
2023-05-31 18:46:15.213 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-05-31 18:46:15.217 - voice - ovos_dinkum_listener.service:_connect_to_bus:379 - INFO - Connected to Mycroft Core message bus
2023-05-31 18:46:19.388 - voice - ovos_plugin_manager.microphone:create:89 - DEBUG - Loaded microphone plugin ovos-microphone-plugin-alsa
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
2023-05-31 18:46:26.178 - voice - ovos_dinkum_listener.plugins:load_stt_module:64 - DEBUG - Using FakeStreamingSTT wrapper with config=None
2023-05-31 18:46:26.253 - voice - ovos_dinkum_listener.service:_before_start:280 - INFO - Starting service...
2023-05-31 18:46:26.980 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-05-31 18:46:26.984 - voice - ovos_dinkum_listener.service:_connect_to_bus:379 - INFO - Connected to Mycroft Core message bus
2023-05-31 18:46:27.008 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:88 - INFO - creating hotword engines
2023-05-31 18:46:27.028 - voice - ovos_plugin_manager.wakewords:load_module:165 - INFO - Loading "hey_mycroft" wake word via ovos-ww-plugin-precise-lite with config: {'module': 'ovos-ww-plugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_precise'}
2023-05-31 18:46:27.330 - voice - ovos_plugin_manager.wakewords:load_module:172 - INFO - Loaded the Wake Word hey_mycroft with module ovos-ww-plugin-precise-lite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2023-05-31 18:46:27.354 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:138 - INFO - Loading hotword: hey_mycroft with engine: <ovos_ww_plugin_precise_lite.PreciseLiteHotwordPlugin object at 0x7f61e21790>
2023-05-31 18:46:27.361 - voice - ovos_plugin_manager.wakewords:load_module:165 - INFO - Loading "wake_up" wake word via ovos-ww-plugin-pocketsphinx with config: {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'W EY K . AH P', 'threshold': 1e-20, 'lang': 'en-us', 'wakeup': True}
2023-05-31 18:46:27.431 - voice - ovos_plugin_manager.wakewords:load_module:172 - INFO - Loaded the Wake Word wake_up with module ovos-ww-plugin-pocketsphinx
2023-05-31 18:46:27.527 - voice - ovos_microphone_plugin_alsa:_run:67 - DEBUG - Opening microphone (device=default, rate=16000, width=2, channels=1)
2023-05-31 18:46:28.086 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:138 - INFO - Loading hotword: wake_up with engine: <ovos_ww_plugin_pocketsphinx.PocketsphinxHotWordPlugin object at 0x7f6478ebd0>
2023-05-31 18:46:28.091 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:167 - WARNING - No stop words loaded
2023-05-31 18:46:28.101 - voice - ovos_dinkum_listener.voice_loop.voice_loop:start:153 - INFO - Listening mode: ListeningMode.WAKEWORD
2023-05-31 18:46:28.105 - voice - ovos_dinkum_listener.service:register_event_handlers:315 - DEBUG - Messagebus events registered
2023-05-31 18:46:28.110 - voice - ovos_dinkum_listener.service:on_started:62 - INFO - DinkumVoiceService started.
2023-05-31 18:46:28.113 - voice - ovos_dinkum_listener.service:run:250 - DEBUG - Service started
2023-05-31 18:46:28.117 - voice - ovos_dinkum_listener.service:on_ready:54 - INFO - DinkumVoiceService is ready.
2023-05-31 18:46:28.120 - voice - ovos_dinkum_listener.service:run:254 - INFO - Service ready
2023-05-31 18:46:28.124 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:177 - INFO - Starting loop in mode: ListeningMode.WAKEWORD
```

After changing `lang` from `en-us` to `fr-fr`:

```
2023-05-31 18:46:57.816 - voice - ovos_config.config:_on_file_change:320 - INFO - Ignoring non-config file change: /home/ovos/.config/mycroft/4913
2023-05-31 18:46:57.842 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-05-31 18:46:57.848 - voice - ovos_config.config:_on_file_change:323 - INFO - /home/ovos/.config/mycroft/mycroft.conf changed on disk
2023-05-31 18:46:57.857 - voice - ovos_config.config:_on_file_change:324 - DEBUG - Calling 1 callbacks
2023-05-31 18:46:57.875 - voice - ovos_dinkum_listener.service:reload_configuration:840 - INFO - Maybe reloading configuration
2023-05-31 18:46:57.881 - voice - ovos_dinkum_listener.service:reload_configuration:848 - DEBUG - Lock Acquired
2023-05-31 18:46:57.895 - voice - ovos_dinkum_listener.service:on_alive:58 - INFO - DinkumVoiceService is alive.
2023-05-31 18:46:57.900 - voice - ovos_dinkum_listener.service:reload_configuration:855 - INFO - Reloading STT
2023-05-31 18:46:57.905 - voice - ovos_dinkum_listener.service:reload_configuration:857 - DEBUG - old=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'en-us'}
2023-05-31 18:46:58.086 - voice - ovos_dinkum_listener.plugins:load_stt_module:64 - DEBUG - Using FakeStreamingSTT wrapper with config=None
2023-05-31 18:46:58.094 - voice - ovos_dinkum_listener.service:reload_configuration:864 - DEBUG - new=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'en-us'}
2023-05-31 18:46:58.099 - voice - ovos_dinkum_listener.service:reload_configuration:867 - INFO - Reloading Fallback STT
2023-05-31 18:46:58.114 - voice - ovos_dinkum_listener.service:on_ready:54 - INFO - DinkumVoiceService is ready.
2023-05-31 18:46:58.120 - voice - ovos_dinkum_listener.service:reload_configuration:927 - INFO - Reload Completed
2023-05-31 18:46:58.124 - voice - ovos_config.config:_on_file_change:320 - INFO - Ignoring non-config file change: /home/ovos/.config/mycroft/.mycroft.conf.swp
```

**Comment by goldyfruit** [comment]
With https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/161

Initial start:
```
2023-05-31 19:01:27.305 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-05-31 19:01:27.463 - OVOS - ovos_utils.configuration:get_xdg_base:76 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-05-31 19:01:31.249 - voice - ovos_dinkum_listener.service:__init__:123 - INFO - Starting Voice Service
2023-05-31 19:01:31.400 - voice - ovos_dinkum_listener.service:on_alive:58 - INFO - DinkumVoiceService is alive.
2023-05-31 19:01:31.404 - voice - ovos_dinkum_listener.service:_before_start:280 - INFO - Starting service...
2023-05-31 19:01:31.421 - voice - ovos_bus_client.conf:load_message_bus_config:19 - DEBUG - Loading message bus configs
2023-05-31 19:01:31.426 - voice - ovos_dinkum_listener.service:_connect_to_bus:372 - DEBUG - Starting bus connection
2023-05-31 19:01:31.474 - voice - ovos_bus_client.client.client:on_open:85 - DEBUG - Connected
2023-05-31 19:01:31.507 - voice - ovos_bus_client.session:from_message:184 - DEBUG - Creating default session on reference
2023-05-31 19:01:31.542 - voice - ovos_bus_client.session:reset_default_session:225 - INFO - New Default Session Start: 2f2a283b-0be0-45f8-adb6-02b40f660a5a
2023-05-31 19:01:31.878 - voice - ovos_config.config:_on_file_change:320 - INFO - Ignoring non-config file change: /home/ovos/.config/mycroft/.mycroft.conf.swx
2023-05-31 19:01:31.884 - voice - ovos_config.config:_on_file_change:320 - INFO - Ignoring non-config file change: /home/ovos/.config/mycroft/.mycroft.conf.swp
2023-05-31 19:01:32.167 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-05-31 19:01:32.172 - voice - ovos_dinkum_listener.service:_connect_to_bus:379 - INFO - Connected to Mycroft Core message bus
2023-05-31 19:01:32.183 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'module': 'ovos-microphone-plugin-alsa', 'lang': 'fr-fr'}
2023-05-31 19:01:32.187 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'module': 'ovos-microphone-plugin-alsa', 'lang': 'fr-fr'}
2023-05-31 19:01:37.851 - voice - ovos_plugin_manager.microphone:create:89 - DEBUG - Loaded microphone plugin ovos-microphone-plugin-alsa
2023-05-31 19:01:37.865 - voice - ovos_plugin_manager.utils.config:get_plugin_config:31 - DEBUG - Loaded configuration: {'sample_rate': 16000, 'mic_meter_ipc': False, 'record_wake_words': True, 'save_utterances': True, 'wake_word_upload': {'disable': True, 'url': ''}, 'microphone': {'module': 'ovos-microphone-plugin-alsa'}, 'VAD': {'silence_method': 'vad_and_ratio', 'speech_seconds': 0.1, 'silence_seconds': 0.5, 'before_seconds': 0.5, 'min_seconds': 1, 'max_current_ratio_threshold': 2, 'initial_energy_threshold': 1000.0, 'module': 'ovos-vad-plugin-silero', 'ovos-vad-plugin-silero': {'threshold': 0.2}, 'ovos-vad-plugin-webrtcvad': {'vad_mode': 2}, 'ovos-vad-plugin-precise': {'debug': True}}, 'retry_mic_init': True, 'mute_during_output': False, 'duck_while_listening': 0.3, 'phoneme_duration': 120, 'multiplier': 1.0, 'energy_ratio': 1.5, 'wake_word': 'hey_mycroft', 'stand_up_word': 'wake_up', 'recording_timeout': 10.0, 'recording_timeout_with_silence': 0.3, 'instant_listen': True, 'continuous_listen': False, 'hybrid_listen': False, 'listen_timeout': 45}
2023-05-31 19:01:37.869 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'threshold': 0.2, 'module': 'ovos-vad-plugin-silero'}
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ovos/.venv/lib/python3.11/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
2023-05-31 19:01:43.749 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:01:44.575 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:01:44.578 - voice - ovos_dinkum_listener.plugins:load_stt_module:64 - DEBUG - Using FakeStreamingSTT wrapper with config=None
2023-05-31 19:01:44.585 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:01:44.592 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'module': 'ovos-stt-plugin-vosk', 'lang': 'fr-fr'}
2023-05-31 19:01:44.642 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:01:45.445 - voice - ovos_stt_plugin_vosk:download_model:144 - INFO - Downloading model for vosk https://alphacephei.com/vosk/models/vosk-model-small-fr-pguyot-0.3.zip
2023-05-31 19:01:45.451 - voice - ovos_stt_plugin_vosk:download_model:145 - INFO - this might take a while
2023-05-31 19:02:09.314 - voice - ovos_stt_plugin_vosk:download_model:150 - INFO - Model downloaded to /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/HCLr.fst /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/word_boundary.int
2023-05-31 19:02:14.869 - voice - ovos_dinkum_listener.plugins:load_fallback_stt:83 - DEBUG - Using FakeStreamingSTT wrapper with config={}
2023-05-31 19:02:14.904 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:02:16.994 - voice - ovos_dinkum_listener.service:_before_start:280 - INFO - Starting service...
2023-05-31 19:02:20.866 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-05-31 19:02:20.871 - voice - ovos_dinkum_listener.service:_connect_to_bus:379 - INFO - Connected to Mycroft Core message bus
2023-05-31 19:02:20.892 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:88 - INFO - creating hotword engines
2023-05-31 19:02:20.904 - voice - ovos_microphone_plugin_alsa:_run:67 - DEBUG - Opening microphone (device=default, rate=16000, width=2, channels=1)
2023-05-31 19:02:22.356 - voice - ovos_plugin_manager.utils.config:get_plugin_config:31 - DEBUG - Loaded configuration: {'hey_mycroft': {'module': 'ovos-ww-plugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_precise'}, 'hey_mycroft_precise': {'module': 'ovos-ww-plugin-precise', 'version': '0.3', 'model': 'https://github.com/MycroftAI/precise-data/raw/models-dev/hey-mycroft.tar.gz', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_vosk'}, 'hey_mycroft_vosk': {'module': 'ovos-ww-plugin-vosk', 'samples': ['hey mycroft', 'hey microsoft', 'hey mike roft', 'hey minecraft'], 'rule': 'fuzzy', 'listen': True, 'fallback_ww': 'hey_mycroft_pocketsphinx'}, 'hey_mycroft_pocketsphinx': {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'HH EY . M AY K R AO F T', 'threshold': 1e-90, 'lang': 'en-us', 'listen': True}, 'wake_up': {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'W EY K . AH P', 'threshold': 1e-20, 'lang': 'en-us', 'wakeup': True}}
2023-05-31 19:02:22.373 - voice - ovos_plugin_manager.wakewords:load_module:165 - INFO - Loading "hey_mycroft" wake word via ovos-ww-plugin-precise-lite with config: {'module': 'ovos-ww-plugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_precise'}
2023-05-31 19:02:22.386 - voice - ovos_plugin_manager.utils.config:get_plugin_config:31 - DEBUG - Loaded configuration: {'hey_mycroft': {'module': 'ovos-ww-plugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_precise'}}
2023-05-31 19:02:28.166 - voice - ovos_plugin_manager.wakewords:load_module:172 - INFO - Loaded the Wake Word hey_mycroft with module ovos-ww-plugin-precise-lite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2023-05-31 19:02:28.607 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:138 - INFO - Loading hotword: hey_mycroft with engine: <ovos_ww_plugin_precise_lite.PreciseLiteHotwordPlugin object at 0x7f7ebdd910>
2023-05-31 19:02:28.629 - voice - ovos_plugin_manager.utils.config:get_plugin_config:31 - DEBUG - Loaded configuration: {'hey_mycroft': {'module': 'ovos-ww-plugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_precise'}, 'hey_mycroft_precise': {'module': 'ovos-ww-plugin-precise', 'version': '0.3', 'model': 'https://github.com/MycroftAI/precise-data/raw/models-dev/hey-mycroft.tar.gz', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_vosk'}, 'hey_mycroft_vosk': {'module': 'ovos-ww-plugin-vosk', 'samples': ['hey mycroft', 'hey microsoft', 'hey mike roft', 'hey minecraft'], 'rule': 'fuzzy', 'listen': True, 'fallback_ww': 'hey_mycroft_pocketsphinx'}, 'hey_mycroft_pocketsphinx': {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'HH EY . M AY K R AO F T', 'threshold': 1e-90, 'lang': 'en-us', 'listen': True}, 'wake_up': {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'W EY K . AH P', 'threshold': 1e-20, 'lang': 'en-us', 'wakeup': True}}
2023-05-31 19:02:28.634 - voice - ovos_plugin_manager.wakewords:load_module:165 - INFO - Loading "wake_up" wake word via ovos-ww-plugin-pocketsphinx with config: {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'W EY K . AH P', 'threshold': 1e-20, 'lang': 'en-us', 'wakeup': True}
2023-05-31 19:02:28.641 - voice - ovos_plugin_manager.utils.config:get_plugin_config:31 - DEBUG - Loaded configuration: {'wake_up': {'module': 'ovos-ww-plugin-pocketsphinx', 'phonemes': 'W EY K . AH P', 'threshold': 1e-20, 'lang': 'en-us', 'wakeup': True}}
2023-05-31 19:02:28.946 - voice - ovos_plugin_manager.wakewords:load_module:172 - INFO - Loaded the Wake Word wake_up with module ovos-ww-plugin-pocketsphinx
2023-05-31 19:02:29.354 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:138 - INFO - Loading hotword: wake_up with engine: <ovos_ww_plugin_pocketsphinx.PocketsphinxHotWordPlugin object at 0x7f81675450>
2023-05-31 19:02:29.362 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:167 - WARNING - No stop words loaded
2023-05-31 19:02:29.415 - voice - ovos_dinkum_listener.voice_loop.voice_loop:start:153 - INFO - Listening mode: ListeningMode.WAKEWORD
2023-05-31 19:02:29.422 - voice - ovos_dinkum_listener.service:register_event_handlers:315 - DEBUG - Messagebus events registered
2023-05-31 19:02:29.441 - voice - ovos_dinkum_listener.service:on_started:62 - INFO - DinkumVoiceService started.
2023-05-31 19:02:29.447 - voice - ovos_dinkum_listener.service:run:250 - DEBUG - Service started
2023-05-31 19:02:29.453 - voice - ovos_dinkum_listener.service:on_ready:54 - INFO - DinkumVoiceService is ready.
2023-05-31 19:02:29.457 - voice - ovos_dinkum_listener.service:run:254 - INFO - Service ready
2023-05-31 19:02:29.463 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:177 - INFO - Starting loop in mode: ListeningMode.WAKEWORD
```

After changing lang from `fr-fr` to `fr-ca`:

```
2023-05-31 19:03:08.154 - voice - ovos_config.config:_on_file_change:320 - INFO - Ignoring non-config file change: /home/ovos/.config/mycroft/4913
2023-05-31 19:03:08.208 - voice - ovos_config.models:load_local:108 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-05-31 19:03:08.216 - voice - ovos_config.config:_on_file_change:323 - INFO - /home/ovos/.config/mycroft/mycroft.conf changed on disk
2023-05-31 19:03:08.223 - voice - ovos_config.config:_on_file_change:324 - DEBUG - Calling 1 callbacks
2023-05-31 19:03:08.248 - voice - ovos_dinkum_listener.service:reload_configuration:840 - INFO - Maybe reloading configuration
2023-05-31 19:03:08.254 - voice - ovos_dinkum_listener.service:reload_configuration:848 - DEBUG - Lock Acquired
2023-05-31 19:03:08.270 - voice - ovos_dinkum_listener.service:on_alive:58 - INFO - DinkumVoiceService is alive.
2023-05-31 19:03:08.283 - voice - ovos_dinkum_listener.service:reload_configuration:855 - INFO - Reloading STT
2023-05-31 19:03:08.289 - voice - ovos_dinkum_listener.service:reload_configuration:857 - DEBUG - old=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.318 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.544 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.631 - voice - ovos_dinkum_listener.plugins:load_stt_module:64 - DEBUG - Using FakeStreamingSTT wrapper with config=None
2023-05-31 19:03:08.643 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.649 - voice - ovos_dinkum_listener.service:reload_configuration:864 - DEBUG - new=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.656 - voice - ovos_dinkum_listener.service:reload_configuration:867 - INFO - Reloading Fallback STT
2023-05-31 19:03:08.662 - voice - ovos_dinkum_listener.service:reload_configuration:869 - DEBUG - old=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:08.670 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'module': 'ovos-stt-plugin-vosk', 'lang': 'fr-ca'}
2023-05-31 19:03:08.734 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/HCLr.fst /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo /home/ovos/.local/share/vosk/vosk-model-small-fr-pguyot-0.3/word_boundary.int
2023-05-31 19:03:16.534 - voice - ovos_dinkum_listener.plugins:load_fallback_stt:83 - DEBUG - Using FakeStreamingSTT wrapper with config={}
2023-05-31 19:03:16.561 - voice - ovos_plugin_manager.utils.config:get_plugin_config:27 - DEBUG - Loaded configuration: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:17.223 - voice - ovos_dinkum_listener.service:reload_configuration:877 - DEBUG - new=<class 'ovos_dinkum_listener.plugins.FakeStreamingSTT'>: {'url': 'http://192.168.1.227:8080/stt', 'module': 'ovos-stt-plugin-server', 'lang': 'fr-fr'}
2023-05-31 19:03:17.240 - voice - ovos_dinkum_listener.service:on_ready:54 - INFO - DinkumVoiceService is ready.
2023-05-31 19:03:17.246 - voice - ovos_dinkum_listener.service:reload_configuration:927 - INFO - Reload Completed

```

**Comment by goldyfruit** [comment]
Same behaviour.

**Review by JarbasAl — APPROVED** [review]

**Comment by goldyfruit** [comment]
Tested and working.

**Review by goldyfruit — APPROVED** [review]

**Pull request merged**
